FROM php:7.4-fpm-alpine

ARG PIWIGO_VERSION=11.1.0
ARG PIWIGO_SHA512=0ad7561ea69fd6942c8e958d3de9ab993626fd66b06a4d23883732924a5bf66314099db540ede73b0769c210cac35542d9b601abf5e932a9e6118870175d6d2c

RUN set -ex; \
	apk add --no-cache \
		bash \
		imagemagick

# Install required PHP extensions
RUN set -ex; \
	\
		apk add --no-cache --virtual .build-deps \
		libjpeg-turbo-dev \
		libpng-dev \
	; \
	\
	docker-php-ext-configure gd --with-jpeg; \
	docker-php-ext-install \
		exif \
		gd \
		mysqli \
	; \
	\
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --virtual .piwigo-phpext-rundeps $runDeps; \
	apk del .build-deps

VOLUME /var/www/html

ENV PIWIGO_VERSION $PIWIGO_VERSION
ENV PIWIGO_SHA512 $PIWIGO_SHA512

RUN set -eu; \
	curl -o piwigo.tar.gz -SL "https://github.com/Piwigo/Piwigo/archive/${PIWIGO_VERSION}.tar.gz"; \
	echo "$PIWIGO_SHA512 *piwigo.tar.gz" | sha512sum -c -; \
	# upstream tarball include ./Piwigo-${PIWIGO_VERSION}/
	tar -xzf piwigo.tar.gz -C /usr/src/; \
	mv /usr/src/Piwigo-${PIWIGO_VERSION} /usr/src/piwigo; \
	rm piwigo.tar.gz; \
	# Does not exist in tarball but is required
	chown -R www-data:www-data /usr/src/piwigo

COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["php-fpm"]
