FROM php:7.1-fpm-alpine

ARG PIWIGO_VERSION=2.9.2
ARG PIWIGO_SHA512=95714ea12d67e20e00bc03b221e5bb597d7be133fe676c3617c60845c55d73ef000a81f6d43289179193f826000748ba908b29cac60bcb70572ee96d9b3e44f9

RUN set -ex; \
	apk add --no-cache \
		bash \
		imagemagick

# Install required PHP extensions
RUN set -ex; \
	\
		apk add --no-cache --virtual .build-deps \
		libjpeg-turbo-dev \
		libpng-dev \
	; \
	\
	docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
	docker-php-ext-install \
		exif \
		gd \
		mysqli \
	; \
	\
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --virtual .piwigo-phpext-rundeps $runDeps; \
	apk del .build-deps

VOLUME /var/www/html

ENV PIWIGO_VERSION $PIWIGO_VERSION
ENV PIWIGO_SHA512 $PIWIGO_SHA512

RUN set -eu; \
	curl -o piwigo.tar.gz -SL "https://github.com/Piwigo/Piwigo/archive/${PIWIGO_VERSION}.tar.gz"; \
	echo "$PIWIGO_SHA512 *piwigo.tar.gz" | sha512sum -c -; \
	# upstream tarball include ./Piwigo-${PIWIGO_VERSION}/
	tar -xzf piwigo.tar.gz -C /usr/src/; \
	mv /usr/src/Piwigo-${PIWIGO_VERSION} /usr/src/piwigo; \
	rm piwigo.tar.gz; \
	# Does not exist in tarball but is required
	chown -R www-data:www-data /usr/src/piwigo

COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["php-fpm"]
