{if isset($ADVICE_ABOUT)}
<div class="content">
  <h3>{'An_advice_about'|@translate} {$ADVICE_ABOUT}</h3>
    <h4>{$ADVICE_TEXT}</h4>
    <table summary="Admin advices summary">
    <tr><td style="text-align: left; width: 50%;">
    {foreach from=$More item=advice}
      {$advice}<BR />
    {/foreach}
    <br />
    </td><td style="text-align: right; width: 20%;">
    {if isset($thumbnail.IMAGE)}
    <a href="{$thumbnail.U_MODIFY}" title="{'link_info_image'|@translate}">
    <img class="thumbnail" src="{$thumbnail.IMAGE}"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"></a>
    </td><td style="text-align: left;">
    <img src="{$themeconf.icon_dir}/{$thumbnail.NAME}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Name'|@translate}<br />
    <img src="{$themeconf.icon_dir}/{$thumbnail.COMMENT}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Description'|@translate}<br />
    <img src="{$themeconf.icon_dir}/{$thumbnail.AUTHOR}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Author'|@translate}<br />
    <img src="{$themeconf.icon_dir}/{$thumbnail.CREATE_DATE}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Creation date'|@translate}<br />
    <img src="{$themeconf.icon_dir}/{$thumbnail.METADATA}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Metadata'|@translate}<br />
    <img src="{$themeconf.icon_dir}/{$thumbnail.TAGS}check.png"
	       alt="{$thumbnail.IMAGE_ALT}" title="{$thumbnail.IMAGE_TITLE}"> {'Tags'|@translate} ({$thumbnail.NUM_TAGS})
    {/if}
  </td>
  </tr>
 
  <tr>
  <td colspan=2>{$smarty.now|date_format:"%A, %B %e, %Y - %r"} --- Templates generated by <a href="http://www.smarty.net/" onclick="window.open(this.href, ''); return false;">Smarty</a> {$smarty.version}</td>
  </tr>
  </table>

</div>
{/if}